#!/bin/bash

juju-log "SiteWhere API relation has changed."

sitewhere_api_host=`relation-get hostname`
sitewhere_api_port=`relation-get port`

# Do not bother with the rest if hostname was not passed.
[ -z "$sitewhere_api_host" ] && echo "Skipping SiteWhere API state update. Hostname not passed." && exit 0;

# Stop the server if already running.
$CHARM_DIR/hooks/stop

# Execute Java code to create SiteWhere state JSON file.
/usr/bin/java -jar /opt/loadtest/juju-tools.jar sitewhereApiState $sitewhere_api_host $sitewhere_api_port > /opt/loadtest/sitewhere.state
if [ $? -ne 0 ]; then
  juju-log "Error running Java command for extracting SiteWhere API state to file."
  exit 1
fi

# Handle case where there were errors generating SiteWhere API state.
sw_err=$(cat /opt/loadtest/sitewhere.state | jq '.error')
if [ "$sw_err" != "null" ]; then
  juju-log "Error marshaling SiteWhere API configuration file."
  juju-log $sw_err
  exit 1
fi

# Start the server.
$CHARM_DIR/hooks/start

