#!/bin/bash

# Must have stored SiteWhere configuration state to know whether we can start server.
if [ -f /opt/loadtest/loadtest.state ]; then

  juju-log "Found load test configuration state file."

else 

  juju-log "Can not start. Load test configuration state not found.";
  exit 0;

fi

juju-log "Testing whether SiteWhere APIs are configured."
if [ -f /opt/loadtest/sitewhere.state ]; then

  juju-log "Linked to remote SiteWhere APIs."

else 

  juju-log "Load test requires access to SiteWhere APIs, but no relation established."
  status-set blocked "Waiting for SiteWhere API relation to be established."
  exit 0;

fi

juju-log "Testing whether MQTT is configured."
mqtt_conf=$(cat /opt/loadtest/loadtest.state | jq '.protocolsConfiguration.usesMqtt')
if [ "$mqtt_conf" == "true" ]; then

  # Verify that a MQTT relationship exists if SiteWhere is configured to use it.
  if [ -f /opt/loadtest/mqtt.state ]; then

    juju-log "Using a MQTT configuration."

  else 

    juju-log "Load test configured for MQTT, but no relation established."
    status-set blocked "Waiting for MQTT relation to be established."
    exit 0;

  fi

fi

/usr/bin/java -jar /opt/loadtest/juju-tools.jar loadTestProperties > /opt/loadtest/conf/loadtest/loadtest.properties
if [ $? -ne 0 ]; then
  juju-log "Error running Java command to generate load test properties file."
  exit 1
fi
chown sitewhere:sitewhere /opt/loadtest/conf/loadtest/loadtest.properties

# Remove existing exploded war if it exists.
rm -rf /opt/loadtest/webapps/sitewhere-load-test-1.0.5

juju-log "Starting SiteWhere Load Test Node."
service loadtest start
status-set active "SiteWhere load test node started."
