options:
  config-url:
    type: string
    default: https://goo.gl/M4rQF3
    description: |
      URL that points to an external SiteWhere Load Test Node configuration 
      which will be copied to the node.

