#!/bin/bash

# Stop the server if already running.
$CHARM_DIR/hooks/stop

# Get rid of existing SiteWhere state file.
rm -f /opt/sitewhere/sitewhere.state

# Process remote configuration file if set.
sw_config_url=`config-get config-url`
if [ -n "$sw_config_url" ]; then

  echo "Updating configuration file from $sw_config_url."
  /usr/bin/java -jar /opt/sitewhere/juju-tools.jar loadRemoteConfig $sw_config_url > /opt/sitewhere/conf/sitewhere/sitewhere-server.xml

  if [ $? -ne 0 ]; then

    juju-log "Error copying configuration file from remote URL."
    exit 1

  fi
fi

# Update SiteWhere state file.
if [ -f /opt/sitewhere/conf/sitewhere/sitewhere-server.xml ]; then

  chown sitewhere:sitewhere /opt/sitewhere/conf/sitewhere/sitewhere-server.xml

  /opt/sitewhere/sitewhereState.sh
  if [ $? -ne 0 ]; then

    rm -f /opt/sitewhere/sitewhere.state
    exit 1
   
  fi

fi

# Set Java memory options used by Tomcat.
sw_java_heap_min_mb=`config-get java-min-heap-mb`
sw_java_heap_max_mb=`config-get java-max-heap-mb`
sw_java_permgen_min_mb=`config-get java-min-permgen-mb`
sw_java_permgen_max_mb=`config-get java-max-permgen-mb`

echo "export CATALINA_OPTS=\"-Xms${sw_java_heap_min_mb}M -Xmx${sw_java_heap_max_mb}M -XX:PermSize=${sw_java_permgen_min_mb}m -XX:MaxPermSize=${sw_java_permgen_max_mb}m\"" > /opt/sitewhere/bin/setenv.sh
chown sitewhere:sitewhere /opt/sitewhere/bin/setenv.sh
chmod 755 /opt/sitewhere/bin/setenv.sh

# Restart the server.
$CHARM_DIR/hooks/start
